name: test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dev: ^1.0.0
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  hooks_riverpod: ^2.6.1
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit: ^4.7.2
  retrofit_generator: ^9.7.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/